### ISSUE TITLE
Support for 3D-Wavelet decompositions?

### ISSUE THREAD

**Issue by homerjed** [v0lta/PyTorch-Wavelet-Toolbox#30]
Hi - this looks really cool! Just wondering if there is any plan for wavelet decompositions for 3D tensors?

**Comment by v0lta** [comment]
For the moment I think the priority must be to extend test coverage to further improve the code we already have.
In the long run, absolutely yes! The goal of this project is to provide Pytorch code that covers PyWavelet functionality completely.

**Comment by v0lta** [comment]
I have started to implement 3d transformation in the https://github.com/v0lta/PyTorch-Wavelet-Toolbox/tree/3dwavedec branch.

**Comment by homerjed** [comment]
Incredible! Thank you. I will try it out now!

**Comment by v0lta** [comment]
Thanks, if you run into problems or observe any unexpected behaviour please let me know.
