### ISSUE TITLE
Wavelet packet transform -urgent help required

### ISSUE THREAD

**Issue by urja02** [v0lta/PyTorch-Wavelet-Toolbox#43]
Hello, i was working on a research project and i wanted to ask you what is the exact output of the wavelet packet transform . Do we get outputs such that they can directly be concatenatd with convolution layer? I need to fuse the frequency domain features with spatial domain.I need more information about how the wavelet packet transform outputs look like. 
Thank you in advance for your reply

**Comment by v0lta** [comment]
Dear @urja02,
Are you working with the two-dimensional packet transform?

You could use an example to explore the output shapes. I.e.:
``` python
from itertools import product
import ptwt, pywt, torch
import numpy as np
import scipy.misc
 
face = np.transpose(scipy.misc.face()[:256, :256, :],
                [2, 0, 1]).astype(np.float64)
pytorch_face = torch.tensor(face).unsqueeze(1)
packets = ptwt.WaveletPacket2D(pytorch_face, pywt.Wavelet("Haar"))

level = 3
paths = list(product(["a", "h", "v", "d"], repeat=level))
packet_list = []
for node in paths:
     packet = torch.squeeze(packets["".join(node)], dim=1)
     packet_list.append(packet)
wp_pt = torch.stack(packet_list, dim=1)
```
Should give you the shape: `[3, 64, 32, 32]` for wp_pt.
You can concatenate wavelet packets and convolution filters.
See https://rdcu.be/cUIRt for an example of where this is useful. Table 1 in particular presents a possible architecture.

**Comment by urja02** [comment]
Hello, thank you so much  for your reply. Yes i have gone through this
paper,could you please give me and insight on how the the packets are
combined with the filters?  The paper talks about wavelet coefficients
which are compared,I used the same code as in the deepfake and it worked
but im not getting the intuitive idea behind it.

**Comment by urja02** [comment]
Yes i am working with 2d packet transform.

**Comment by v0lta** [comment]
The wavelet transforms in CNN create an invariant representation. I think the idea first appeared in https://arxiv.org/pdf/1203.1513.pdf . Adding an invariant representation can speed up convergence if the final result was going to resemble wavelets. In the deep-fake detection paper, we also saw drops in the amount of training data required.

**Comment by urja02** [comment]
Thank you for the explanation. I have a question, what does invariant
representation mean?

**Comment by v0lta** [comment]
The representation is not optimized, so all filter values are constant.

**Comment by urja02** [comment]
I have added the wavelet packet transform units in a residual manner in
efficientdet.  I have added it just before the biFPN layer.  Does the
invariant representation help in object detection.

**Comment by urja02** [comment]
Does that mean that an object can be detected even when the scene changes

**Comment by v0lta** [comment]
It means the wavelet filters are not optimized. The transformation is invertible it does not lose information. When the scene changes the output of the wavelet-transform changes accordingly. I haven't tried wavelet representations in object recognition tasks. Generally, static representations tend to help more on smaller data sets.
