### ISSUE TITLE
Stationary Wavelet Transform 

### ISSUE THREAD

**Issue by matciotola** [v0lta/PyTorch-Wavelet-Toolbox#53]
Hi,
I really appreciate your work!
I wonder if it is possible to expand this toolbox, inserting the SWT (in particular swt2 and iswt2), already implemented in the pywt library.
Thanks,
Matteo

**Comment by v0lta** [comment]
Dear @matteo, this would certainly be a nice feature, but for the moment we need to focus on wrapping up version https://github.com/v0lta/PyTorch-Wavelet-Toolbox/pull/46 . This would be something for v0.1.6 and will take time.

**Comment by v0lta** [comment]
As always, contributions are welcome!

**Comment by v0lta** [comment]
https://github.com/v0lta/PyTorch-Wavelet-Toolbox/blob/main/tests/test_swt.py is a start. More will come eventually.

**Comment by matciotola** [comment]
Thank you so much!
