### ISSUE TITLE
Adaptive 1D wavelet filters

### ISSUE THREAD

**Issue by harshaUwm163** [v0lta/PyTorch-Wavelet-Toolbox#58]
Hello, Thank you for the great repo! 

I was wondering if there are plans for adding adaptive 1D wavelet filters with examples?

Thanks again for the wonderful effort!

**Comment by v0lta** [comment]
https://github.com/v0lta/PyTorch-Wavelet-Toolbox/tree/main/examples/network_compression does this.

**Comment by harshaUwm163** [comment]
Got it Thanks! I am closing this issue!!
