### ISSUE TITLE
Avoid adding of a batch dim on 2d signals.

### ISSUE THREAD

**Issue by felixblanke** [v0lta/PyTorch-Wavelet-Toolbox#92]
For 1d signals the coefficients as well as reconstructed signals keep the same number of dimensions as the original input signal.
However, for 2d signals with only 2 axes we currently always add a superfluous batch dimension, i.e. `[H, W] -> [1, H, W]`.

This seems inconsistent.

We can address this by introducing a functionality similiar to `ptwt.conv_transform._postprocess_result_list_dec1d` for higher dimensions.

**Comment by v0lta** [comment]
https://github.com/v0lta/PyTorch-Wavelet-Toolbox/pull/93 is merged.
